EWPP-743: Remove corporate body restriction for content owner and sit…
openeuropa/oe_corporate_site_info pull request #15
Opened 2021-02-04 17:28 UTC by sergepavle

…e owner field.

2021-02-09 09:02 UTC, 22Alexandra approved these changes, later dismissed

2021-02-11 07:45 UTC, drishu requested changes
lets add one test for any of the new items

2021-02-11 12:14 UTC, drishu approved these changes

2021-02-12 12:54 UTC, 22Alexandra approved these changes

2021-02-19 07:17 UTC, merged