OEL-2115: Update to PHP 8.1
openeuropa/oe_corporate_site_info pull request #29
Opened 2023-01-04 18:38 UTC by brummbar

2023-01-09 15:31 UTC, 22Alexandra approved these changes, later dismissed

2023-01-13 15:36 UTC, nagyad requested changes

2023-01-13 15:36 UTC, nagyad commented on composer.json
> +        "openeuropa/rdf_skos": "dev-EWPP-2892"
For now can be changed to 1.x.

2023-01-16 13:33 UTC, 22Alexandra approved these changes

2023-01-16 13:35 UTC, nagyad approved these changes

2023-01-16 13:44 UTC, merged