EWPP-615: Add Content Owners related methods.
openeuropa/oe_corporate_site_info pull request #9
Opened 2020-12-16 14:28 UTC by georgebaev

This functionality adds the Content Owner relate methods. 

The Behat test is extended with a new Scenario which tests the Content Owner related functionality.

2021-01-08 09:46 UTC, nagyad requested changes

2021-01-08 09:46 UTC, nagyad commented on src/SiteInformation.php
> +  public function hasContentOwners(): bool {
According to my understanding, this configuration serves as a default value definition. I would reflect this in the name of the function like: hasDefaultContentOwners().

2021-01-08 09:46 UTC, nagyad commented on src/SiteInformation.php
> +  public function getContentOwners(): array {
getDefaultContentOwners()

2021-01-08 09:46 UTC, nagyad commented on src/SiteInformationInterface.php
> +   * Check whether content owners are set for the site.
Check whether default content owners are set for the site.

2021-01-08 09:46 UTC, nagyad commented on src/SiteInformationInterface.php
> +   * Get current content owner SKOS concept entities.
Get the default content owners set for the site.

2021-01-08 09:46 UTC, nagyad commented on tests/src/Behat/CorporateSiteInformationContext.php
> +   * @Given I set the content owner to :label
I set the site default content owner to

2021-01-08 09:46 UTC, nagyad commented on tests/src/Behat/CorporateSiteInformationContext.php
> +  public function setContentOwner(string $label): void {
setSiteDefaultContentOwner() otherwise it would make me think you set the field default value without the site in it.

2021-01-08 09:46 UTC, nagyad commented on tests/src/Behat/CorporateSiteInformationContext.php
> +   * Assert content owner.
Here you also check for the site default content owner.

2021-01-08 09:46 UTC, nagyad commented on tests/src/Behat/CorporateSiteInformationContext.php
> +   * @Then the content owner should be set to :label
... the site default content owner should be set to

2021-01-11 08:15 UTC, upchuk requested changes

2021-01-11 08:15 UTC, upchuk commented on src/SiteInformationInterface.php
> +   * @return \Drupal\rdf_skos\Entity\Concept[]
ConceptInterface[]

2021-01-11 12:48 UTC, upchuk approved these changes

2021-01-11 16:14 UTC, nagyad approved these changes

2021-01-12 15:03 UTC, merged